\set ON_ERROR_STOP on

CREATE ROLE efata_schema_collector_fixture
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE efata_runtime_fixture
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE efata_role_a
    NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE efata_privileged_role
    NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION BYPASSRLS;

GRANT efata_role_a TO efata_runtime_fixture
    WITH INHERIT TRUE, SET TRUE, ADMIN FALSE;
GRANT efata_privileged_role TO efata_role_a
    WITH INHERIT FALSE, SET FALSE, ADMIN FALSE;

REVOKE CONNECT, TEMPORARY ON DATABASE efata_collector_fixture_test FROM PUBLIC;
GRANT CONNECT ON DATABASE efata_collector_fixture_test TO
    efata_fixture_bootstrap,
    efata_schema_collector_fixture,
    efata_runtime_fixture;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO efata_schema_collector_fixture, efata_runtime_fixture;

CREATE TYPE public.business_item_status AS ENUM ('ACTIVE', 'DISABLED');
CREATE DOMAIN public.tenant_key AS text
    CHECK (VALUE <> '');

CREATE TABLE public.alembic_version (
    version_num varchar(64) PRIMARY KEY
);
INSERT INTO public.alembic_version(version_num)
VALUES ('009_audit_evidence_ledger');

CREATE TABLE public.business_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tenant_id public.tenant_key NOT NULL,
    name text NOT NULL,
    status public.business_item_status NOT NULL DEFAULT 'ACTIVE',
    updated_at timestamptz NOT NULL DEFAULT pg_catalog.now(),
    CONSTRAINT business_items_pk PRIMARY KEY (id),
    CONSTRAINT business_items_name_tenant_uq UNIQUE (tenant_id, name),
    CONSTRAINT business_items_name_nonempty CHECK (pg_catalog.length(name) > 0)
);

INSERT INTO public.business_items(tenant_id, name)
VALUES ('tenant-a', 'fixture secret row');

ALTER TABLE public.business_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_items FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation
ON public.business_items
TO efata_runtime_fixture
USING (tenant_id::text = pg_catalog.current_setting('efata.tenant_id', true))
WITH CHECK (tenant_id::text = pg_catalog.current_setting('efata.tenant_id', true));

CREATE FUNCTION public.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $$
BEGIN
    NEW.updated_at := pg_catalog.now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER business_items_touch
BEFORE UPDATE ON public.business_items
FOR EACH ROW
EXECUTE FUNCTION public.touch_updated_at();

CREATE FUNCTION public.secure_item_count(tenant text)
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
    SELECT pg_catalog.count(*)
    FROM public.business_items
    WHERE tenant_id::text = tenant
$$;

REVOKE ALL ON FUNCTION public.secure_item_count(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.secure_item_count(text) TO efata_runtime_fixture;

CREATE VIEW public.business_items_view AS
SELECT id, tenant_id, name, status, updated_at
FROM public.business_items;

GRANT SELECT, INSERT, UPDATE ON public.business_items TO efata_runtime_fixture;
GRANT SELECT ON public.business_items_view TO efata_runtime_fixture;
GRANT USAGE ON SEQUENCE public.business_items_id_seq TO efata_runtime_fixture;
GRANT USAGE ON TYPE public.business_item_status TO efata_runtime_fixture;
GRANT USAGE ON TYPE public.tenant_key TO efata_runtime_fixture;

GRANT SELECT ON public.alembic_version TO efata_schema_collector_fixture;

CREATE SCHEMA efata_fixture_meta AUTHORIZATION efata_fixture_bootstrap;
REVOKE ALL ON SCHEMA efata_fixture_meta FROM PUBLIC;

CREATE TABLE efata_fixture_meta.target_attestation (
    fixture_runtime_id text NOT NULL,
    connection_binding_id text NOT NULL,
    fixture_nonce text NOT NULL
);

INSERT INTO efata_fixture_meta.target_attestation(
    fixture_runtime_id,
    connection_binding_id,
    fixture_nonce
)
VALUES (
    :'fixture_runtime_id',
    :'connection_binding_id',
    :'fixture_nonce'
);

GRANT USAGE ON SCHEMA efata_fixture_meta TO efata_schema_collector_fixture;
GRANT SELECT ON efata_fixture_meta.target_attestation TO efata_schema_collector_fixture;
